### ISSUE TITLE
Immediate exit after successful login

### ISSUE THREAD

**Issue by cserem** [rgladwell/imap-upload#1]
This version prematurely exists without any error message if I give it the right credentials to gmail.  If I purposely give it wrong login data it displays an error message. (tried with --gmail and with imaps://imap.gmail.com/ ). Not tested with other providers.

**Comment by rgladwell** [comment]
Can you give more information? What command line arguments are you using exactly?

**Comment by cserem** [comment]
- Debian 7.8
- Python 2.7.3
- cmd: python ./imap_upload.py --gmail --box="import1/somemapp" mydira/to_be_imported
Please let me know if you need additional infomation/testing about/with the enviroment.

**Comment by jellopuddingstick** [comment]
The issue seems to be that line 387 is indented so as to be part of the if err: conditional. Unindenting this line allows the script to run successfully.
