### ISSUE TITLE
Document how to get around Google Security lockout

### ISSUE THREAD

**Issue by hanryhu** [rgladwell/imap-upload#23]
On the CLI, I saw the following error after `python imap_upload.py --gmail --box imported mbox_file.mbox`:
```
Username: user@gmail.com
Password: ........
Connecting to imap.gmail.com:993.
IMAP4 error: [AUTHENTICATIONFAILED] Invalid credentials (Failure)
```

The error is related to what Google calls "Less secure apps".  I fixed it by going to [My Account -> Security](https://myaccount.google.com/u/9/security) and then choosing "Turn on access (not recommended)":
![image](https://user-images.githubusercontent.com/38797540/103041772-6127f280-4545-11eb-9255-0d2674191838.png)

**Comment by rgladwell** [comment]
You can access your Gmail account with disabling security by creating an application-specific password:

https://support.google.com/accounts/answer/185833?hl=en

Does this fix the issue for you?

**Comment by Behinder** [comment]
That setting is no longer available which is annoying. People should have right to choose, too much security means it's often inconvenient to use services.

**Comment by rgladwell** [comment]
Sorry to hear they deprecated this setting. I don't think there is anything we can do about this, so I'm going to close this.
