### ISSUE TITLE
--google-takeout is a mandatory option

### ISSUE THREAD

**Issue by poldy79** [rgladwell/imap-upload#38]
As --google-takeout-language has a default 'en', the code suspects, that the option was set by the user and complains, that --google-takeout was not supplied. So currently (684cd23) --google-takeout is a mandatory option. 

Do you know how to check if the user had supplied --google-takeout-language on cmdline or if it is just the default? 
We might could just ignore google-takeout-language, if google-takeout was not supplied... suggestions?

**Comment by poldy79** [comment]
I have created https://github.com/rgladwell/imap-upload/pull/40 to solve this issue

**Comment by rgladwell** [comment]
Thanks @poldy79.
